### ISSUE TITLE
Slider iç yazıları dikkatle responsive boyların tamamında ayarlanmalı. Slider iconlarının yerleşimleri düzeltilmeli.

### ISSUE THREAD

**Issue by LanistaSoftware** [LanistaSoftware/Gochem#75]
![photo_2020-04-20_09-43-09](https://user-images.githubusercontent.com/59227701/79721639-5ef10280-82eb-11ea-8d2d-0b46c473173c.jpg)

**Comment by bozkurt30** [comment]
tamam landı
