### ISSUE TITLE
Box boyutları mobile için yükseltilmeli. Box References slider içerik sığmalı.

### ISSUE THREAD

**Issue by LanistaSoftware** [LanistaSoftware/Gochem#76]
![photo_2020-04-20_09-44-11](https://user-images.githubusercontent.com/59227701/79721761-96f84580-82eb-11ea-9a0c-d45dd31d39fd.jpg)

**Comment by bozkurt30** [comment]
Yapıldı

**Comment by bozkurt30** [comment]
bitti
