### ISSUE TITLE
sosyal medya iconları yukarı header arası boşluk azaltılmalı.

### ISSUE THREAD

**Issue by LanistaSoftware** [LanistaSoftware/Gochem#81]
![image](https://user-images.githubusercontent.com/59227701/79722373-9ca25b00-82ec-11ea-828b-eff8da1298dc.png)

**Comment by bozkurt30** [comment]
yapıldı,  search ve social ayrı yapıldı. socials.vue silindi

**Comment by bozkurt30** [comment]
bitti
